### ISSUE TITLE
92%

### ISSUE THREAD

**Issue by lkitrossky** [mazurkin/codility#1]
Hi! This is very interesting but still gives 92%. That is what codility says:

case name: "less_than_max_rotations"
description: optimal number of rotations is less than K
result: WRONG ANSWER
Numbers:  got 30 expected 32

Till now could not find a test case to reproduce it.
Great thanks, Levi

**Comment by lkitrossky** [comment]
Sorry, I did not see that you yourself wrote 92%. Did you find an exact test case to reproduce? Thanks,

**Comment by mazurkin** [comment]
@lkitrossky No, I'm curious what is that failing test case as well - no idea

**Comment by lkitrossky** [comment]
Shall try. I got only silver for Manganum. Did you try it?

**Comment by mazurkin** [comment]
No I didn't - changed the job and now have a lot of work to do
